default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: your_app_development

test:
  <<: *default
  database: your_app_test

production:
  <<: *default
  database: your_app_production
  username: your_app
  password: <%= ENV['YOUR_APP_DATABASE_PASSWORD'] %>
